### ISSUE TITLE
push: Unnable access remote when `gdrive_user_credentials_file` is set into `.dvc/config` 

### ISSUE THREAD

**Issue by maltempi** [iterative/dvc-gdrive#31]
# Bug Report

## Description
When attempting to use DVC with Google Drive credentials set in a customized file (`gdrive_user_credentials_file `), an error is encountered. The issue arises when executing DVC commands that touch the remote storage, such as `dvc push` or `dvc pull`.

### Reproduce

1.  Given a working Google Drive authentication info into `./gdrive/mydataset-credentials.json` and the following `.dvc/config` file:
```toml
[core]
    remote = mydataset
['remote "mydataset"']
    url = gdrive://${folder_id}
    gdrive_user_credentials_file = ./.gdrive/mydataset-credentials.json
```` 

2. Try to use a command that touches the remote storage, such as `push` or `pull`
```console
dvc push
```

### Actual result:
```console
$ dvc push
ERROR: unexpected error - Setting save_credentials_file should be type <class 'str'>                                                                        

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

### Expected

DVC should use my credentials previously set.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 3.4.0 (pip)
------------------------
Platform: Python 3.10.9 on Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.3.3
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        gdrive (pydrive2 = 1.16.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
        Global: /home/thiago.maltempi/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: nfs on 10.20.200.1:/exports/home
Caches: local
Remotes: gdrive
Workspace directory: nfs on 10.20.200.1:/exports/home
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/8059f048374a2688cbb2ff3c68b23a96
```

### Troubleshooting
The error is thrown from `\pydrive2\settings.py` (see https://github.com/iterative/PyDrive2/blob/main/pydrive2/settings.py#L170).  
So I added a `print` there, and got this:
```python
print('---->', value, type(value))
'''----> ${my_full_path}/./.gdrive/mydataset-credentials.json <class 'dvc.config_schema.RelPath'>'''
```

The fix may probably be in the `dvc` end, before calling `pydrive2`.

**Comment by efiop** [comment]
@maltempi Could you post full log for `dvc push -v`, please?

**Comment by maltempi** [comment]
Hi @efiop  , here it goes:

```
$ dvc push -v
2023-07-04 13:03:28,624 DEBUG: v3.4.0 (pip), CPython 3.10.9 on Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
2023-07-04 13:03:28,624 DEBUG: command: ${REPLACED}miniconda3/bin/dvc push -v
2023-07-04 13:03:28,933 DEBUG: Preparing to transfer data from '${REPLACED}/.dvc/cache/files/md5' to '1z7WXNjtpiAJiQrpCB9P_DTHeLcRgSJZJ/files/md5'
2023-07-04 13:03:28,933 DEBUG: Preparing to collect status from '1z7WXNjtpiAJiQrpCB9P_DTHeLcRgSJZJ/files/md5'
2023-07-04 13:03:28,933 DEBUG: Collecting status from '1z7WXNjtpiAJiQrpCB9P_DTHeLcRgSJZJ/files/md5'
2023-07-04 13:03:29,096 ERROR: unexpected error - Setting save_credentials_file should be type <class 'str'>                                                
Traceback (most recent call last):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/repo/push.py", line 92, in push
    result = self.cloud.push(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 196, in push
    t, f = self._push(default_objs, jobs=jobs, odb=odb)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 212, in _push
    return self.transfer(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 167, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/transfer.py", line 209, in transfer
    status = compare_status(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 178, in compare_status
    dest_exists, dest_missing = status(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 149, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 412, in oids_exist
    remote_size, remote_oids = self._estimate_remote_size(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 294, in _estimate_remote_size
    remote_oids = set(iter_with_pbar(oids))
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 284, in iter_with_pbar
    for oid in oids:
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 250, in _oids_with_limit
    for oid in self._list_oids(prefixes=prefixes, jobs=jobs):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 237, in _list_oids
    for path in self._list_prefixes(prefixes=prefixes, jobs=jobs):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 216, in _list_prefixes
    yield from self.fs.find(paths, batch_size=jobs, prefix=prefix)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 429, in find
    yield from self.fs.find(path)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/funcy/objects.py", line 47, in __get__
    return prop.__get__(instance, type)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_gdrive/__init__.py", line 105, in fs
    return _GDriveFileSystem(self._path, **self._settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/fs/spec.py", line 226, in __init__
    google_auth = _client_auth(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/fs/spec.py", line 124, in _client_auth
    auth = GoogleAuth(settings=settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/auth.py", line 197, in __init__
    ValidateSettings(self.settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 130, in ValidateSettings
    _ValidateSettingsStruct(data, SETTINGS_STRUCT)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 145, in _ValidateSettingsStruct
    _ValidateSettingsElement(data, struct, key)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 189, in _ValidateSettingsElement
    _ValidateSettingsElement(data, struct, reqkey)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 189, in _ValidateSettingsElement
    _ValidateSettingsElement(data, struct, reqkey)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 171, in _ValidateSettingsElement
    raise InvalidConfigError(f"Setting {key} should be type {data_type}")
pydrive2.settings.InvalidConfigError: Setting save_credentials_file should be type <class 'str'>

2023-07-04 13:03:29,135 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-07-04 13:03:29,135 DEBUG: Removing '${REPLACED}workspace/awave3d/.V6p4H9A5nNc8AtUDBBFLVg.tmp'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}workspace/awave3d/.V6p4H9A5nNc8AtUDBBFLVg.tmp'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}workspace/awave3d/.V6p4H9A5nNc8AtUDBBFLVg.tmp'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}/.dvc/cache/files/md5/.oUN8sbcMrSxKKr2q2DD83c.tmp'
2023-07-04 13:03:29,150 DEBUG: Version info for developers:
DVC version: 3.4.0 (pip)
------------------------
Platform: Python 3.10.9 on Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.3.3
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        gdrive (pydrive2 = 1.16.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
        Global: ${REPLACED}.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: nfs on 10.20.200.1:/exports/home
Caches: local
Remotes: gdrive
Workspace directory: nfs on 10.20.200.1:/exports/home
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/8059f048374a2688cbb2ff3c68b23a96
```

Notice I replace all my paths by ${REPLACED} ;-)

**Comment by maltempi** [comment]
Hi @efiop , here it goes:

```
$ dvc push -v
2023-07-04 13:03:28,624 DEBUG: v3.4.0 (pip), CPython 3.10.9 on Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
2023-07-04 13:03:28,624 DEBUG: command: ${REPLACED}miniconda3/bin/dvc push -v
2023-07-04 13:03:28,933 DEBUG: Preparing to transfer data from '${REPLACED}/.dvc/cache/files/md5' to '${REPLACED}/files/md5'
2023-07-04 13:03:28,933 DEBUG: Preparing to collect status from '${REPLACED}/files/md5'
2023-07-04 13:03:28,933 DEBUG: Collecting status from '${REPLACED}/files/md5'
2023-07-04 13:03:29,096 ERROR: unexpected error - Setting save_credentials_file should be type <class 'str'>                                                
Traceback (most recent call last):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/repo/push.py", line 92, in push
    result = self.cloud.push(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 196, in push
    t, f = self._push(default_objs, jobs=jobs, odb=odb)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 212, in _push
    return self.transfer(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 167, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/transfer.py", line 209, in transfer
    status = compare_status(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 178, in compare_status
    dest_exists, dest_missing = status(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 149, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 412, in oids_exist
    remote_size, remote_oids = self._estimate_remote_size(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 294, in _estimate_remote_size
    remote_oids = set(iter_with_pbar(oids))
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 284, in iter_with_pbar
    for oid in oids:
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 250, in _oids_with_limit
    for oid in self._list_oids(prefixes=prefixes, jobs=jobs):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 237, in _list_oids
    for path in self._list_prefixes(prefixes=prefixes, jobs=jobs):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 216, in _list_prefixes
    yield from self.fs.find(paths, batch_size=jobs, prefix=prefix)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 429, in find
    yield from self.fs.find(path)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/funcy/objects.py", line 47, in __get__
    return prop.__get__(instance, type)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_gdrive/__init__.py", line 105, in fs
    return _GDriveFileSystem(self._path, **self._settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/fs/spec.py", line 226, in __init__
    google_auth = _client_auth(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/fs/spec.py", line 124, in _client_auth
    auth = GoogleAuth(settings=settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/auth.py", line 197, in __init__
    ValidateSettings(self.settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 130, in ValidateSettings
    _ValidateSettingsStruct(data, SETTINGS_STRUCT)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 145, in _ValidateSettingsStruct
    _ValidateSettingsElement(data, struct, key)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 189, in _ValidateSettingsElement
    _ValidateSettingsElement(data, struct, reqkey)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 189, in _ValidateSettingsElement
    _ValidateSettingsElement(data, struct, reqkey)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 171, in _ValidateSettingsElement
    raise InvalidConfigError(f"Setting {key} should be type {data_type}")
pydrive2.settings.InvalidConfigError: Setting save_credentials_file should be type <class 'str'>

2023-07-04 13:03:29,135 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-07-04 13:03:29,135 DEBUG: Removing '${REPLACED}workspace/awave3d/.V6p4H9A5nNc8AtUDBBFLVg.tmp'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}workspace/awave3d/.V6p4H9A5nNc8AtUDBBFLVg.tmp'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}workspace/awave3d/.V6p4H9A5nNc8AtUDBBFLVg.tmp'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}/.dvc/cache/files/md5/.oUN8sbcMrSxKKr2q2DD83c.tmp'
2023-07-04 13:03:29,150 DEBUG: Version info for developers:
DVC version: 3.4.0 (pip)
------------------------
Platform: Python 3.10.9 on Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.3.3
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        gdrive (pydrive2 = 1.16.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
        Global: ${REPLACED}.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: nfs on 10.20.200.1:/exports/home
Caches: local
Remotes: gdrive
Workspace directory: nfs on 10.20.200.1:/exports/home
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/8059f048374a2688cbb2ff3c68b23a96
```

**Comment by maltempi** [comment]
Hi @efiop 
```
$ dvc push -v
2023-07-04 13:03:28,624 DEBUG: v3.4.0 (pip), CPython 3.10.9 on Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
2023-07-04 13:03:28,624 DEBUG: command: ${REPLACED}miniconda3/bin/dvc push -v
2023-07-04 13:03:28,933 DEBUG: Preparing to transfer data from '${REPLACED}/.dvc/cache/files/md5' to '${REPLACED}/files/md5'
2023-07-04 13:03:28,933 DEBUG: Preparing to collect status from '${REPLACED}/files/md5'
2023-07-04 13:03:28,933 DEBUG: Collecting status from '${REPLACED}/files/md5'
2023-07-04 13:03:29,096 ERROR: unexpected error - Setting save_credentials_file should be type <class 'str'>                                                
Traceback (most recent call last):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/repo/push.py", line 92, in push
    result = self.cloud.push(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 196, in push
    t, f = self._push(default_objs, jobs=jobs, odb=odb)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 212, in _push
    return self.transfer(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc/data_cloud.py", line 167, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/transfer.py", line 209, in transfer
    status = compare_status(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 178, in compare_status
    dest_exists, dest_missing = status(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 149, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 412, in oids_exist
    remote_size, remote_oids = self._estimate_remote_size(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 294, in _estimate_remote_size
    remote_oids = set(iter_with_pbar(oids))
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 284, in iter_with_pbar
    for oid in oids:
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 250, in _oids_with_limit
    for oid in self._list_oids(prefixes=prefixes, jobs=jobs):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 237, in _list_oids
    for path in self._list_prefixes(prefixes=prefixes, jobs=jobs):
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/db.py", line 216, in _list_prefixes
    yield from self.fs.find(paths, batch_size=jobs, prefix=prefix)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 429, in find
    yield from self.fs.find(path)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/funcy/objects.py", line 47, in __get__
    return prop.__get__(instance, type)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/dvc_gdrive/__init__.py", line 105, in fs
    return _GDriveFileSystem(self._path, **self._settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/fs/spec.py", line 226, in __init__
    google_auth = _client_auth(
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/fs/spec.py", line 124, in _client_auth
    auth = GoogleAuth(settings=settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/auth.py", line 197, in __init__
    ValidateSettings(self.settings)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 130, in ValidateSettings
    _ValidateSettingsStruct(data, SETTINGS_STRUCT)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 145, in _ValidateSettingsStruct
    _ValidateSettingsElement(data, struct, key)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 189, in _ValidateSettingsElement
    _ValidateSettingsElement(data, struct, reqkey)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 189, in _ValidateSettingsElement
    _ValidateSettingsElement(data, struct, reqkey)
  File "${REPLACED}miniconda3/lib/python3.10/site-packages/pydrive2/settings.py", line 171, in _ValidateSettingsElement
    raise InvalidConfigError(f"Setting {key} should be type {data_type}")
pydrive2.settings.InvalidConfigError: Setting save_credentials_file should be type <class 'str'>

2023-07-04 13:03:29,135 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-07-04 13:03:29,135 DEBUG: Removing '${REPLACED}'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}'
2023-07-04 13:03:29,136 DEBUG: Removing '${REPLACED}'
2023-07-04 13:03:29,150 DEBUG: Version info for developers:
DVC version: 3.4.0 (pip)
------------------------
Platform: Python 3.10.9 on Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.3.3
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        gdrive (pydrive2 = 1.16.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
        Global: ${REPLACED}.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: nfs on 10.20.200.1:/exports/home
Caches: local
Remotes: gdrive
Workspace directory: nfs on 10.20.200.1:/exports/home
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/{replaced}
```

**Comment by efiop** [comment]
@maltempi Thanks! Looks like we are forgetting to convert to a string path somewhere. Taking a look...

**Comment by efiop** [comment]
@maltempi A workaround for you might be to specify an absolute path temporarily. E.g. using `.dvc/config.local`.

**Comment by efiop** [comment]
Ah, looks like it is pydrive2's fault. They should really use `isinstance` and not `type()` there. I'll prepare a patch in a sec.

**Comment by efiop** [comment]
@maltempi Would you mind installing pydrive2 from my branch and see if that fixes it for you?

```
pip install git+https://github.com/iterative/pydrive2.git@pydrive2-type
```

**Comment by maltempi** [comment]
Hi @efiop , I just tested the version in your branch, and it is working as expected! :) 

Any plans for when this will be officially released? 

Thank you very much you guys from the Iterative community, always ready to help!

**Comment by efiop** [comment]
@maltempi Thank you! We'll trigger a release for pydrive2 in a a few minutes and will update the rest.

**Comment by efiop** [comment]
@maltempi New pydrive2 release (1.16.1) is out and should get picked up automatically in fresh installs.

Thanks again for the feedback! 🙏
